library(purrr)

# Argument = project directory

args <- commandArgs(trailingOnly = TRUE)
dir <- args[1]
output_file <- args[2]
if (substr(dir, nchar(dir), nchar(dir)) != "/") {
  dir <- paste0(dir, "/")
}

# Get all VCF files generated by "convert_cychp.R"
samples <- list.files(dir, pattern = "*.vcf")
print(samples)
# Creating variables necessary to set up the dataframes
first <- TRUE
FID <- 0

# Loop through the samples, and adding them to the ped & map dataframes
for(ind in samples){
  gt <- read.table(paste(dir, ind, sep=""), header = TRUE, sep="\t")
  if(first){
    first <- FALSE
    # Constructing the data.frames
    map_fmt_df <- data.frame("CHROM" = gt$CHROM,
                             "RSID" = gt$ID,
                             "CM" = 0,
                             "POS" = gt$POS
                             )
  }
  
  # Creating variables to add to .PED file

}

# Writing .MAP & .PED files to PLINK directory.
write.table(map_fmt_df, output_file, quote = F, sep = "\t", row.names = F, col.names = F)
